#!/bin/bash -eux

sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
yum install -y epel-release  # Adds extra repos
yum upgrade -y

yum install -y bzip2         # Required to compile gcc
yum install -y gcc-c++       # Required to compile Node.js v7-
yum install -y make          # Allows compilation
yum install -y ccache        # Allows caching
yum install -y devtoolset-12 # Includes gcc 12.1.1
